version: '3'
services:
  app:
    image: trankwilizator/tafl:latest
    hostname: localhost
    ports: 
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tafl_db
      SPRING_DATASOURCE_USERNAME: trankwilizator
      SPRING_DATASOURCE_PASSWORD: 517881m
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trankwilizator
      POSTGRES_PASSWORD: 517881m
      POSTGRES_DB: tafl_db
