version: '3'
services:
  app:
    image: openjdk:21-slim
    volumes:
      - ./target/tafl-1.0.0.jar:/app/tafl.jar
    ports:
      - 8080:8080
    depends_on:
      - db
    command: ["java", "-jar", "/app/tafl.jar"]
  db:
    image: postgres
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database_name
    volumes:
      - ./data:/var/lib/postgresql/data
