name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21

      - name: Build and Test
        run: |
          ./mvnw clean package
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.trankwilizator }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag tafl trankwilizator/tafl:latest
          docker push trankwilizator/tafl:latest


      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker Image
        run: |
          docker build -t my-app .
          docker-compose build

      - name: Run Docker Containers
        run: docker-compose up -d
