name: Check Application Runnable

on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'
          cache: 'maven'

      - name: Start PostgreSQL container
        run: |
          docker run --name pg -d -p 5432:5432 \
            -e POSTGRES_USER=trankwilizator \
            -e POSTGRES_PASSWORD=517881m \
            -e POSTGRES_DB=tafl_db \
            postgres:15-alpine

      - name: Build the application
        run: mvn clean package

      - name: Stop pg container
        run: docker stop pg

      - name: Start the application container
        run: |
          docker-compose up --build -d
          docker-compose logs -f > app_logs.txt &
        
      - name: Check Swagger API availability
        run: |
          retries=0
          while ! curl --fail --silent --output /dev/null http://localhost:8080/v3/api-docs; do
          retries=$((retries+1))
          if [ $retries -gt 20 ]; then
           echo "Swagger API is not available within the allotted time."
           exit 1
          fi
          echo "Waiting for Swagger API to become available..."
          sleep 1
          done

      - name: Display application logs
        run: cat app_logs.txt

      - name: Check deployment status
        run: |
          if [ $? -eq 0 ]; then
            echo "Deployment successful"
          else
            echo "Deployment failed"
            exit 1
          fi
