name: Publish Swagger documentation

on:
  push:
    branches:
      - '*'

jobs:
  publish-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Start PostgreSQL container
        run: |
          docker run --name pg -d -p 5432:5432 \
            -e POSTGRES_USER=trankwilizator \
            -e POSTGRES_PASSWORD=517881m \
            -e POSTGRES_DB=tafl_db \
            postgres:15-alpine

      - name: Build the application
        run: mvn clean package

      - name: Stop pg container
        run: docker stop pg

      - name: Start the application container
        run: docker-compose up --build -d

      - name: Wait for application to start
        run: sleep 30

      - name: Install Swagger CLI
        uses: mpetrunic/swagger-cli-action@v1.0.0

      - name: Determine API version
        id: version
        run: |
          echo "::set-output name=version::1.0.0"

      - name: Extract Swagger specification
        run: |
          curl -o swagger.json http://localhost:8080/v3/api-docs
          mv swagger.json ${{ github.workspace }}/swagger.json

      - name: Publish Swagger documentation
        run: |
          swagger-cli push ${{ github.workspace }}/swagger.json \
            --api-key ${{ secrets.SWAGGER_API_KEY }} \
            --owner musiev_maksim \
            --api tafl \
            --version ${{ steps.version.outputs.version }}
