name: Publish Swagger documentation

on:
  push:
    branches:
      - '*'

jobs:
  publish-swagger:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Start PostgreSQL container
        run: |
          docker run --name pg -d -p 5432:5432 \
            -e POSTGRES_USER=trankwilizator \
            -e POSTGRES_PASSWORD=517881m \
            -e POSTGRES_DB=tafl_db \
            postgres:15-alpine

      - name: Build the application
        run: mvn clean package

      - name: Stop pg container
        run: docker stop pg

      - name: Start the application container
        run: docker-compose up --build -d
        
      - name: Wait for application to start
        run: sleep 20

      - name: Clean Swagger file
        run: rm -f ${{ github.workspace }}/swagger.json

      - name: Import Swagger specification
        run: curl -o ${{ github.workspace }}/swagger.json http://localhost:8080/v3/api-docs

      - name: Fetch tags
        run: git fetch --tags

      - name: Get current version
        id: get_version
        run: |
          current_version=$(git describe --abbrev=0 --tags --always HEAD)
          echo "Current version: $current_version"
          echo "version=$current_version" >> $GITHUB_STATE




      - name: Split version
        id: split_version
        run: |
          major=$(echo ${{ steps.get_version.outputs.version }} | cut -d. -f1)
          minor=$(echo ${{ steps.get_version.outputs.version }} | cut -d. -f2)
          patch=$(echo ${{ steps.get_version.outputs.version }} | cut -d. -f3)
          echo "::set-output name=major::$major"
          echo "::set-output name=minor::$minor"
          echo "::set-output name=patch::$patch"

      - name: Calculate new version
        id: calculate_version
        run: |
          patch=$(( ${{ steps.split_version.outputs.patch }} + 1 ))
          new_version="${{ steps.split_version.outputs.major }}.${{ steps.split_version.outputs.minor }}.$patch"
          echo "New version: $new_version"
          echo "::set-output name=patch::$patch"
          echo "::set-output name=new_version::$new_version"

      - name: Update Swagger version
        run: |
          version="v${{ steps.calculate_version.outputs.new_version }}"
          jq --arg newVersion "$version" '.info.version = $newVersion' ${{ github.workspace }}/swagger.json > ${{ github.workspace }}/swagger_temp.json && mv ${{ github.workspace }}/swagger_temp.json ${{ github.workspace }}/swagger.json

      - name: Show Swagger content
        run: cat ${{ github.workspace }}/swagger.json

      - name: Publish Swagger documentation
        id: publish_swagger
        run: |
          echo "::set-output name=swagger_file_path::${{ github.workspace }}/swagger.json"
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.SWAGGER_API_KEY }}" \
          -d @"${{ github.workspace }}/swagger.json" \
          https://api.swaggerhub.com/apis/musiev_maksim/tafl

