name: Publish Swagger documentation

on:
  push:
    branches:
      - '*'

jobs:
  publish-swagger:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
          java-version: 17
          distribution: 'oracle'

    - name: Start PostgreSQL container
      run: |
          docker run --name pg -d -p 5432:5432 \
            -e POSTGRES_USER=trankwilizator \
            -e POSTGRES_PASSWORD=517881m \
            -e POSTGRES_DB=tafl_db \
            postgres:15-alpine

    - name: Build the application
      run: mvn clean package
    - name: Stop pg container
      run: docker stop pg

    - name: Start the application container
      run: docker-compose up --build -d
        
    - name: Wait for application to start
      run: sleep 30
  

    - name: Clean Swagger file
      run: rm -f ${{ github.workspace }}/swagger.json

    - name: Import Swagger specification
      run: curl -o ${{ github.workspace }}/swagger.json http://localhost:8080/v3/api-docs

    - name: Get current version
      id: get_version
      run: echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

    - name: Split version
      id: split_version
      run: |
        echo "MAJOR=$(echo ${{ env.VERSION }} | awk -F '.' '{print $1}')" >> $GITHUB_ENV
        echo "MINOR=$(echo ${{ env.VERSION }} | awk -F '.' '{print $2}')" >> $GITHUB_ENV
        echo "PATCH=$(echo ${{ env.VERSION }} | awk -F '.' '{print $3}')" >> $GITHUB_ENV

    - name: Calculate new version
      id: calculate_version
      run: |
        patch=$(( ${{ env.PATCH }} + 1 ))
        echo "PATCH=$patch" >> $GITHUB_ENV
        echo "NEW_VERSION=${{ env.MAJOR }}.${{ env.MINOR }}.$patch" >> $GITHUB_ENV

    - name: Update Swagger version
      run: |
        version="v${{ env.NEW_VERSION }}"
        jq --arg newVersion "$version" '.info.version = $newVersion' ${{ github.workspace }}/swagger.json > ${{ github.workspace }}/swagger_temp.json && mv ${{ github.workspace }}/swagger_temp.json ${{ github.workspace }}/swagger.json

    - name: Display Swagger JSON
      run: cat ${{ github.workspace }}/swagger.json

    - name: Publish Swagger documentation
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
           -H "Authorization: Bearer ${{ secrets.SWAGGER_API_KEY }}" \
         -d @${{ github.workspace }}/swagger.json \
         https://api.swaggerhub.com/apis/musiev_maksim/tafl
        working-directory: ${{ github.workspace }}

