name: Newman tests
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build and Test
    env:
      postman_env_path: ${{ github.workspace }}/postman/env/tafl.postman_environment.json
      log_file_path: ${{ github.workspace }}/docker-compose-logs.txt
      newman_report_path: ${{ github.workspace }}/newman-report.xml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'
          cache: 'maven'

      - name: Start PostgreSQL container
        run: |
          docker run --name pg -d -p 5432:5432 \
            -e POSTGRES_USER=trankwilizator \
            -e POSTGRES_PASSWORD=517881m \
            -e POSTGRES_DB=tafl_db \
            postgres:15-alpine

      - name: Build the application
        run: mvn clean package

      - name: Stop pg container
        run: docker stop pg

      - name: Start the application container
        run: |
          docker-compose up --build -d
          docker-compose logs -f > ${{ env.log_file_path }} &

      - name: Wait for application to start
        run: sleep 15

      - name: Install Newman CLI
        run: npm install -g newman

      - name: Run API tests
        run: |
          newman run "${{ github.workspace }}/postman/collections/permanent user password change test.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
          newman run "${{ github.workspace }}/postman/collections/test device status.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
          newman run "${{ github.workspace }}/postman/collections/test not authenticated logout.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
          newman run "${{ github.workspace }}/postman/collections/test not authenticated request.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
          newman run "${{ github.workspace }}/postman/collections/test permit all end-points.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
          newman run "${{ github.workspace }}/postman/collections/test registration already exists permanent user.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
          newman run "${{ github.workspace }}/postman/collections/test release device.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
          newman run "${{ github.workspace }}/postman/collections/test reserve device.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
          newman run "${{ github.workspace }}/postman/collections/test sign in with incorrect password.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
          newman run "${{ github.workspace }}/postman/collections/test sign in with incorrect username.json" -e "$postman_env_path" --reporters cli,junit --reporter-junit-export "$newman_report_path"
        continue-on-error: true

      - name: Log application container output
        if: ${{ always() }}
        run: cat ${{ env.log_file_path }}

      - name: Check deployment status
        run: |
          if [ $? -eq 0 ]; then
            echo "Deployment successful"
          else
            echo "Deployment failed"
            exit 1
          fi

      - name: Upload Newman Report
        uses: actions/upload-artifact@v2
        with:
          name: Newman Report
          path: ${{ env.newman_report_path }}