name: Swagger api to postman collection

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Start PostgreSQL container
        run: |
          docker run --name pg -d -p 5432:5432 \
            -e POSTGRES_USER=trankwilizator \
            -e POSTGRES_PASSWORD=517881m \
            -e POSTGRES_DB=tafl_db \
            postgres:15-alpine

      - name: Build the application
        run: mvn clean package

      - name: Stop pg container
        run: docker stop pg

      - name: Start the application container
        run: docker-compose up --build -d
        
      - name: Wait for application to start
        run: sleep 30

      - name: Download Swagger JSON
        run: |
          curl -o swagger.json http://localhost:8080/v3/api-docs
        env:
          SWAGGER_JSON_URL: http://localhost:8080/v3/api-docs

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create Postman collection
        run: |
          collection_name="My API Collection"
          collection_uid=$(curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
            -d "{\"name\":\"$collection_name\"}" \
            "https://api.getpostman.com/collections" | jq -r '.collection.uid')

          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
            -d "{\"collection\":{\"info\":{\"name\":\"$collection_name\"},\"item\":[{\"name\":\"API\",\"item\":$(jq '.paths | to_entries | map({name:.key, item:.value})' swagger.json)}}]}}" \
            "https://api.getpostman.com/collections/$collection_uid"
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
